name: movies_app_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  broadcast_bloc: ^0.1.0-dev.2
  crypto: ^3.0.3
  dart_frog: ^1.1.0
  dart_frog_web_socket: ^1.0.0
  dart_jsonwebtoken: ^2.13.0
  mongo_dart: ^0.10.0
  movies_app_models:
    path: ../packages/movies_app_models
  shelf_cors_headers: ^0.1.5
  tmdb_api: ^2.2.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
